name: axel
version: '0.0.13'
category: Language, Lisp, Macros, Transpiler
author: Joshua Grosso
maintainer: jgrosso256@gmail.com
copyright: 2020 Joshua Grosso
license: BSD3
github: axellang/axel
synopsis: The Axel programming language.
description: Haskell's semantics, plus Lisp's macros. Meet Axel – a purely functional, extensible, and powerful programming language.
extra-source-files:
  - README.org
  - scripts/**/*
ghc-options:
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-implicit-prelude
  - -Wno-missed-specialisations
  - -Wno-missing-deriving-strategies
  - -Wno-missing-export-lists
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-missing-kind-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-unused-packages
  - -optP-Wno-nonportable-include-path # https://github.com/haskell/cabal/issues/4739
  - -O2
  - -fplugin=Effectful.Plugin
build-tools:
  - hpack:hpack
  - tasty-discover:tasty-discover
dependencies:
  - aeson ==2.0.3.0
  - ansi-terminal ==0.11.3
  - base ==4.16.2.0
  - bytestring ==0.11.3.1
  - containers ==0.6.5.1
  - directory ==1.3.6.2
  - effectful ==1.1.0.0
  - effectful-core ==1.1.0.0
  - effectful-plugin ==1.0.0.0
  - effectful-th ==1.0.0.0
  - extra ==1.7.10
  - filepath ==1.4.2.2
  - ghcid ==0.8.7
  - hashable ==1.4.0.2
  - haskell-src-exts ==1.23.1
  - hedgehog ==1.1.1
  - hpack ==0.35.0
  - hspec ==2.10.0
  - lens ==5.1.1
  - lens-aeson ==1.2.1
  - megaparsec ==9.2.1
  - mono-traversable ==1.0.15.3
  - optparse-applicative ==0.17.0.0
  - prettyprinter ==1.7.1
  - process ==1.6.13.2 # https://www.reddit.com/r/haskellquestions/comments/uj759w/ghc_922_build_error
  - profunctors ==5.6.2
  - random ==1.2.1.1
  - split ==0.2.3.4
  - tasty ==1.4.2.3
  - tasty-discover ==5.0.0
  - tasty-golden ==2.3.5
  - tasty-hedgehog ==1.2.0.0
  - tasty-hspec ==1.2.0.1
  - tasty-hunit ==0.10.0.3
  - template-haskell ==2.18.0.0
  - text ==2.0
  - time ==1.11.1.1
  - transformers ==0.5.6.2
  - typed-process ==0.2.10.1
  - uniplate ==1.6.13
  - vector ==0.12.3.1
  - yaml ==0.11.8.0
data-files:
  - resources/**/*
# NOTE Keep in sync with `.hindent.yaml#extensions` and `.hlint.yaml#extensions`.
default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
library:
  source-dirs: src
  ghc-options: []
  dependencies: []
executables:
  axel:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - axel
tests:
  axel-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - axel
