module Axel.Test.Parse.ASTGen where

import qualified Axel.Parse.AST as AST
import qualified Axel.Sourcemap as SM

import Hedgehog
import qualified Hedgehog.Gen as Gen
import qualified Hedgehog.Range as Range

genExpression :: (MonadGen m) => m SM.Expression
genExpression =
  Gen.recursive
    Gen.choice
    [ AST.LiteralChar AST.AutoGenerated <$> Gen.unicode
    , AST.LiteralInt AST.AutoGenerated <$> Gen.int Range.constantBounded
    , AST.LiteralString AST.AutoGenerated <$>
      Gen.string (Range.linear 0 5) Gen.unicode
    , AST.Symbol AST.AutoGenerated <$> Gen.string (Range.linear 0 5) Gen.alpha
    ]
    [ AST.SExpression AST.AutoGenerated <$>
      Gen.list (Range.linear 0 3) genExpression
    ]
