module AutogeneratedAxelScaffold where

import qualified AutogeneratedAxelMacroDefinitionAndEnvironment
import Axel.Parse.AST

import Unsafe.Coerce (unsafeCoerce)

main :: IO ()
main = do
  result <-
    AutogeneratedAxelMacroDefinitionAndEnvironment.main_AXEL_AUTOGENERATED_FUNCTION_DEFINITION
      (map unsafeCoerce %%%ARGUMENTS%%%)
  putStrLn $ unlines $ map toAxel result
