module Scaffold where

import Axel.Parse.AST
import qualified AutogeneratedAxelMacroDefinitionAndEnvironment

main :: IO ()
main = do
  result <-
    AutogeneratedAxelMacroDefinitionAndEnvironment.%%%MACRO_NAME%%% %%%ARGUMENTS%%%
  putStrLn $ unlines $ map toAxel result
