module AutogeneratedAxelScaffold where

import qualified AutogeneratedAxelMacroDefinitionAndEnvironment
import Axel.Parse.AST
import Axel.Sourcemap

main :: IO ()
main = do
  result <-
    AutogeneratedAxelMacroDefinitionAndEnvironment.main_AXEL_AUTOGENERATED_FUNCTION_DEFINITION %%%ARGUMENTS%%%
  putStrLn $ unlines $ map toAxel result
