module ImportSyntax where
import Axel
import qualified Prelude as AxelRuntime_GHCPrelude
import qualified Axel.Parse.AST as AxelRuntime_AST
import qualified Axel.Sourcemap as AxelRuntime_Sourcemap
import Foo
import Bar(foo,bar,Baz(baz))
import qualified Bar as Baz
import qualified Bar as Baz(foo)
import Quux(foo_AXEL_AUTOGENERATED_MACRO_DEFINITION,bar_AXEL_AUTOGENERATED_MACRO_DEFINITION)