main :: (IO ())
main
  = ((\ aXEL_AUTOGENERATED_IDENTIFIER_0 ->
        (case aXEL_AUTOGENERATED_IDENTIFIER_0 of
             "tada" -> (putStrLn "\127881")
             _ -> (putStrLn "Impossible!")))
       "tada")