set -eu
set -o pipefail

echo "Copying macro header..."
mkdir -p resources/autogenerated/macros
cp src/Axel/Parse/AST.hs resources/autogenerated/macros/AST.hs
echo "Macro header copied!\n"

echo "[WIP] Configure Cabal..."
hpack
stack2cabal
echo "[WIP] Cabal configured!\n"

cabal new-build
cabal new-run axel-exe -- project
cabal new-build
